Channel bindings
frozencemetery/krb5 pull request #1
Opened 2018-08-02 20:15 UTC by cipherboy

- Rebases off of lastest master
- Fixes typo:

```diff
gtd
diff --git a/src/lib/gssapi/generic/gssapi_generic.c b/src/lib/gssapi/generic/gssapi_generic.c
index bc8fd3160..d1a710f9e 100644
--- a/src/lib/gssapi/generic/gssapi_generic.c
+++ b/src/lib/gssapi/generic/gssapi_generic.c
@@ -424,7 +424,7 @@ static struct mech_attr_info_desc {
     },
     {
         oids+38,
-        "GSS_C_MA_CBINDING_CONFIRM",
+        "GSS_C_MA_CBINDING_MAY_CONFIRM",
         "channel-bindings-may-confirm",
         "Mechanism supports may indicate channel binding success.",
     },
```

Feel free to close after merging/rebasing/etc..

2018-08-09 19:05 UTC, cipherboy commented
I believe the detected style issues to be non-issues in practice:

```
$ python2 ./util/cstyle.py -w master
  lib/gssapi/generic/gssapi_ext.h:
      593  8+ spaces in file which uses tabs
      594  8+ spaces in file which uses tabs
      598  8+ spaces in file which uses tabs
      599  8+ spaces in file which uses tabs
      600  8+ spaces in file which uses tabs
      601  8+ spaces in file which uses tabs
  lib/gssapi/spnego/spnego_mech.c:
      702  Preprocessor statement in function body
      717  Preprocessor statement in function body
     3162  Space after cast operator (or inline if/while body)
     3193  Space after cast operator (or inline if/while body)
```

In particular, `lib/gssapi/generic/gssapi_ext.h` appears to use spaces, and in `lib/gssapi/spnego/spnego_mech.c`, 702/717 should disappear at some point and 3162/3193 are for consistency with existing code.

Actually, 702/717 can disappear now with the new changes. Let me try that.

2018-08-09 19:54 UTC, cipherboy commented
Lines 702/717 issues have been fixed as of latest set of commits (patch 4).

2018-08-09 21:22 UTC, frozencemetery requested changes
Thanks for the update!  Some (irritating) changes requested inline.

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/generic/gssapi_generic.c
> +     * TODO: actual OIDs for these.
this

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/generic/gssapi_generic.c
> +     * https://tools.ietf.org/html/draft-ietf-kitten-channel-bound-flag-01
link update please

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/spnego/spnego_mech.c
> +							      &avail_mechs->elements[i],
This line is too long (8-space tabs in this file)

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/spnego/spnego_mech.c
> +	(void) gss_release_oid_set(minor_status, &avail_mechs);
No space after cast

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/spnego/spnego_mech.c
> +		(void) gss_release_oid_set(minor_status, &mechs);
Having to free something that the call allocated on failure isn't generally something we like (because it means the caller has to worry about *where* it failed).  Better if `filter_available_mechs()` leaves mechs unallocated when it fails.  This is why we also NULL out a lot of output parameters at the start of functions (which should be done with mechs in `filter_available_mechs()`).

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/spnego/spnego_mech.c
> +						   preferred_attrs,
krb5 style prefers shoving as many of these on a line as will fit in the character limit.

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi32.def
> +	gss_mech_krb5_wrong	       	@41	DATA
You shouldn't be touching this line

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/spnego/spnego_mech.c
> +	gss_OID_set *mechs)
Indentation on this is wrong

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/spnego/spnego_mech.c
> +	unsigned int i;
`size_t`

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/spnego/spnego_mech.c
> +filter_available_mechs(OM_uint32 *minor_status, gss_OID_set preferred_attrs,
`filter` isn't the greatest name here because the mechs aren't gone, they're just lower priority.  Maybe `prioritize_available_mechs`?  Or something like that?

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/spnego/spnego_mech.c
> +					gss_OID_set *);
Indentation is wrong

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/spnego/spnego_mech.c
> +		    minor_status,
Goes on previous line

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/spnego/spnego_mech.c
> +					   GSS_C_NO_OID_SET,
Shouldn't be on its own line

2018-08-09 21:22 UTC, frozencemetery commented on src/lib/gssapi/spnego/spnego_mech.c
> +
No blank line

2018-08-10 14:52 UTC, cipherboy commented on src/lib/gssapi/generic/gssapi_generic.c
> +     * https://tools.ietf.org/html/draft-ietf-kitten-channel-bound-flag-01
I updated all occurrences of this now.

2018-08-10 14:53 UTC, cipherboy commented on src/lib/gssapi/spnego/spnego_mech.c
> +	(void) gss_release_oid_set(minor_status, &avail_mechs);
Okay, I was following the standard in `get_available_mechs`. I have update this though.

2018-08-10 14:53 UTC, cipherboy commented on src/lib/gssapi/spnego/spnego_mech.c
> +						   preferred_attrs,
I'm not sure that _more_ can fit on line given the character limit... Did I miss something?

2018-08-10 14:53 UTC, cipherboy commented on src/lib/gssapi32.def
> +	gss_mech_krb5_wrong	       	@41	DATA
Yeah, sorry.

2018-08-10 14:56 UTC, cipherboy commented
Okay, I think this is updated. I had a question on the line lengths; do you think these still need to be updated?

2018-08-10 18:41 UTC, frozencemetery commented
Updated branch to 84b219ab5c700d4081b448c056b8954b41a3696e and previous, thanks!

2018-08-10 18:41 UTC, closed without merging

2018-08-10 18:46 UTC, cipherboy commented
Thanks @frozencemetery! :)